config/routes.rb
Rails.application.routes.draw do
  get 'admin/home'
  resources :posts do
  	resources :reviews
  end
  devise_for :users
  #get 'home/index'
  #root 'home#index'
  root to: 'posts#index'
  resources :users
  resources :reviews
  get '/myprofile' => 'users#myprofile'
  get '/admin' => 'admin#home'
  get '/admin/users' => 'admin#users_admin'
  get '/admin/reviews' => 'admin#reviews_admin'
  get '/admin/posts' => 'admin#posts_admin'
  get '/leaderboard' => 'reviews#ordered'
  get '/about' => 'home#about'
  #delete "users/:id" => "users#destroy"

  #resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :reviews do
  #		member do
   #   patch "like", to: "reviews#like"
    #end
  #end
  resources :reviews do
    member do
      patch "upvote", to: "reviews#upvote"
      patch "downvote", to: "reviews#downvote"
    end
  end
end

app/views/admin/_admin_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Admin', admin_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to 'Manage Albums | ', admin_posts_path, class:"nav-link"  %>
       </li>
       <li class="nav-item">
            <li><%= link_to 'Manage Reviews | ', admin_reviews_path, class:"nav-link" %></li>
       </li>
       <li class="nav-item">
            <%= link_to 'Manage Users', admin_users_path, class:"nav-link" %>
       </li>
</ul>
  </div>
</nav>
</br>

app/views/admin/home.html.erb
<%admin_restricted%>
<p id="notice"><%= notice %></p>
<%= render 'admin/admin_nav' %>
<h1 class="text-center">Admin Dashboard</h1>
<ul class="list-group text-center">
  <li class="list-group-item text-center"><%= link_to 'Manage Posts', admin_posts_path %></li>
  <li class="list-group-item text-center"><%= link_to 'Manage Reviews', admin_reviews_path %></li>
  <li class="list-group-item text-center"><%= link_to 'Manage Users', admin_users_path %></li>
</ul>

app/views/admin/posts_admin.html.erb
<%= render 'admin/admin_nav' %>
<h1>Albums Admin</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Album</th>
        <th>About</th>
        <th>Poster</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <%  @posts = Post.all %>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.artist %>'s <%= post.title %></td>
          <td><%= truncate(post.about, :length => 150 )%></td>
          <td><%= link_to post.user.username, post.user %></td>
          <td><%= link_to 'Show', post%></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/reviews_admin.html.erb
<%admin_restricted%>
<p id="notice"><%= notice %></p>
<%= render 'admin/admin_nav' %>
<h1>Reviews Admin</h1>

<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Review</th>
        <th>Reviewer</th>
        <th>Album</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <% @reviews = Review.all %>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= truncate(review.body, :length => 150 )%></td>
          <td><%= review.user.username %></td>
          <td><%= review.post.artist %>'s <%= review.post.title %></td>
          <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/users_admin.html.erb
<%admin_restricted%>
<p id="notice"><%= notice %></p>
<%= render 'admin/admin_nav' %>
<h1>Users Admin</h1>

<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>No of Reviews</th>
        <th>No of Contributions</th>
        <th>Conbtributer</th>
        <th>Admin</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <% @users = User.all %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.email%></td>
          <td><%= user.reviews.count %></td>
          <td><%= user.posts.count%></td>
          <td><%= user.has_role?(:contributer)%></td>
          <td><%= user.has_role?(:admin)%></td>
          <td><%= link_to 'Show', user%></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>