config/routes.rb
Rails.application.routes.draw do
  get 'admin/home'
  resources :posts do
  	resources :reviews
  end
  devise_for :users
  #get 'home/index'
  #root 'home#index'
  root to: 'posts#index'
  resources :users
  resources :reviews
  get '/myprofile' => 'users#myprofile'
  get '/admin' => 'admin#home'
  get '/admin/users' => 'admin#users_admin'
  get '/admin/reviews' => 'admin#reviews_admin'
  get '/admin/posts' => 'admin#posts_admin'
  get '/leaderboard' => 'reviews#ordered'
  get '/about' => 'home#about'
  #delete "users/:id" => "users#destroy"

  #resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :reviews do
  #		member do
   #   patch "like", to: "reviews#like"
    #end
  #end
  resources :reviews do
    member do
      patch "upvote", to: "reviews#upvote"
      patch "downvote", to: "reviews#downvote"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Music Social', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item">
          	<%= link_to 'About Us', about_path, class:"nav-link" %>
       </li>
      <% if user_signed_in? %>
      		<li class="nav-item">
          		<%= link_to 'My Profile', myprofile_path, class:"nav-link" %>
       		</li>
       		<li class="nav-item">
          		<%= link_to 'Top Reviews', leaderboard_path, class:"nav-link" %>
       		</li>    
        <% end %>
    </ul>
    <%= form_tag posts_path, class:"form-inline mx-auto", :method => "get" do %>
  		<%= text_field_tag :search, params[:search], class:"form-control mr-sm-2", placeholder:"artist search" %>
  		<%= submit_tag("Search", :artist => nil, class:"btn btn-outline-success my-2 my-sm-0")%>
	<%end%>
</ul>

    <ul class="navbar-nav mr-right">
    	<% if user_signed_in? %>
    		<li class="nav-item">
          		<%= link_to 'Update Profile', edit_user_registration_path, class:"nav-link" %>
       		</li>
       		<li class="nav-item">
         		 <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        	</li>
        	<%= link_to (image_tag current_user.avatar.url, style: 'height:50px;width:50px;', :title => 'My Profile'), myprofile_path if current_user.avatar?  %>
         <% else %>
       		<li class="nav-item">
         	 	<%= link_to 'Sign In',  new_user_session_path, class:"nav-link" %>
        	</li>
        	<li class="nav-item">
            	<%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        	</li>
        <%end%>
	</ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

<div class="jumbotron">
  	<h2>What is Social Music?</h2>
  	<br/>
  	<p>Social Music is a media site that combines socail media with love of music. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget bibendum quam. Morbi et feugiat quam. Fusce aliquet eros quis fringilla malesuada. Duis tincidunt nulla ac ipsum pulvinar, sed posuere dolor auctor. Cras scelerisque diam eros, in molestie massa rutrum et. Sed sit amet dolor imperdiet, mattis nibh non, gravida metus. Aenean vitae sapien a felis luctus vehicula. Proin ultricies faucibus ante, vel consectetur orci feugiat sit amet. Phasellus non justo dui. Suspendisse elementum dolor non mi euismod mattis. Phasellus nec feugiat est. Pellentesque bibendum posuere erat ac dignissim. Etiam iaculis, elit ac facilisis tristique, nunc nibh sagittis nisi, quis congue dui nulla congue orci. Aenean pretium mollis lectus a vulputate. Duis maximus tortor massa, non porta mi pharetra et.</p>
</div>

<div class="jumbotron">
  <h2>Why Join the Community?</h2>
  <br/>
  <p>Review any of the regularly added albums each week and get rewarded with likes from you fellow reviews. You could even appear on our leaderboard. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget bibendum quam. Morbi et feugiat quam. Fusce aliquet eros quis fringilla malesuada. Duis tincidunt nulla ac ipsum pulvinar, sed posuere dolor auctor. Cras scelerisque diam eros, in molestie massa rutrum et. Sed sit amet dolor imperdiet, mattis nibh non, gravida metus. Aenean vitae sapien a felis luctus vehicula. Proin ultricies faucibus ante, vel consectetur orci feugiat sit amet. Phasellus non justo dui. Suspendisse elementum dolor non mi euismod mattis. Phasellus nec feugiat est. Pellentesque bibendum posuere erat ac dignissim. Etiam iaculis, elit ac facilisis tristique, nunc nibh sagittis nisi, quis congue dui nulla congue orci.</p>
</div>

<div class="jumbotron">
  	<h2>Our Values</h2>
  	<br/>
  	<ul>
  		<li>Provide a vibrant and safe community for music lovers</li>
  		<li>Pellentesque bibendum posuere erat ac dignissim</li>
  		<li>Pellentesque bibendum posuere erat ac dignissim</li>
  		<li>Pellentesque bibendum posuere erat ac dignissim</li>
   	</ul>
</div>

app/views/home/index.html.erb
<h1>Social Musica</h1>
<p>Placeholder First Page</p>