config/routes.rb
Rails.application.routes.draw do
  get 'admin/home'
  resources :posts do
  	resources :reviews
  end
  devise_for :users
  #get 'home/index'
  #root 'home#index'
  root to: 'posts#index'
  resources :users
  resources :reviews
  get '/myprofile' => 'users#myprofile'
  get '/admin' => 'admin#home'
  get '/admin/users' => 'admin#users_admin'
  get '/admin/reviews' => 'admin#reviews_admin'
  get '/admin/posts' => 'admin#posts_admin'
  get '/leaderboard' => 'reviews#ordered'
  get '/about' => 'home#about'
  #delete "users/:id" => "users#destroy"

  #resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :reviews do
  #		member do
   #   patch "like", to: "reviews#like"
    #end
  #end
  resources :reviews do
    member do
      patch "upvote", to: "reviews#upvote"
      patch "downvote", to: "reviews#downvote"
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all.order(cached_votes_score: :desc)
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @post = Post.find(params[:post_id])
    @user = current_user
    #@user = current_user
    #@review = @post.reviews.new(parent_id: params[:parent_id]) **
    #@review = @post.reviews.new(parent_id: params[:parent_id])
    @review = @user.reviews.new(:post_id => @post.id, parent_id: params[:parent_id])
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    #@review = @post.reviews.new(review_params)
    @review = @user.reviews.new(review_params.merge(post_id: @post.id))
    #@review = @user.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @post, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    if (current_user.has_role?(:admin))
      respond_to do |format|
        if @review.update(review_params)
          format.html { redirect_to @review, notice: "Review was successfully updated." }
          format.json { render :show, status: :ok, location: @review }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    if (current_user == @review.user || current_user.has_role?(:admin))
      @review.destroy
      respond_to do |format|
        format.html { redirect_to @review.post, notice: "Review was successfully destroyed." }
        format.json { head :no_content }
      end
       else
        redirect_to root_path
      end
  end

  def like
    @review = Review.find(params[:id])
    if current_user.voted_up_on? @review
      @review.downvote_by current_user
    elsif current_user.voted_down_on? @review
      @review.upvote_by current_user
    else #not voted
      @review.upvote_by current_user
    end
    respond_to do |format|
     format.js
    end 
  end

  def upvote
    @review = Review.find(params[:id])
    if current_user.voted_up_on? @review
      @review.unvote_by current_user
    else
      @review.upvote_by current_user
    end
    render "vote.js.erb"
  end

  def downvote
    @review = Review.find(params[:id])
    if current_user.voted_down_on? @review
      @review.unvote_by current_user
    else
      @review.downvote_by current_user
    end
    render "vote.js.erb"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:body, :parent_id, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{review.id}" do %>
  <%= link_to downvote_review_path(review), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_down_on? review %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
  <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
</svg>
      remove
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
  <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
</svg>
      downvote
    <% end %>
  <% end %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_like_count.html.erb
<%= content_tag "div", id: "like-count-#{review.id}" do %>
  <%= review.cached_votes_score %>
<% end %>

app/views/reviews/_like_link.html.erb
<%= link_to like_review_path(review), method: :patch, remote: true, id: "like-link-#{review.id}" do %>
  <% if current_user.voted_up_on?(review) %>
    UP voted
    <b>
      <%= review.cached_votes_score %>
    </b>
    DOWN vote
  <% elsif current_user.voted_down_on?(review) %>
    UP vote
    <b>
      <%= review.cached_votes_score %>
    </b>
    DOWN voted
  <% else %>
    UP
    <b>
      <%= review.cached_votes_score %>
    </b>
    DOWN
  <% end %>
<% end %>

app/views/reviews/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
  	<p><%= link_to (image_tag reply.user.avatar.url, style: 'height:40px;width:40px;'), reply.user if reply.user.avatar?  %> <%= link_to reply.user.username,  reply.user %> wrote:</p>
    <%= reply.body %>
    <br/><br/>
	<% if current_user == reply.user || current_user.has_role?(:admin) %>
		<%= link_to 'Delete', reply, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
 	<%end%>
  </div>
</div>

app/views/reviews/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@post, @review]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-secondary' %>
      <%= link_to 'Cancel', post_path(@post), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<% unless review.parent_id || !review.persisted? %>
	<div class="card">
  		<div class="card-body">
  		<p><%= link_to (image_tag review.user.avatar.url, style: 'height:40px;width:40px;'), review.user if review.user.avatar?  %> <%= link_to review.user.username,  review.user %> wrote:</p>
    		<p><%= review.body %></p>

    	<% if current_user %>
    <%= render 'reviews/upvote_link', review: review %>
    <%= render 'reviews/like_count', review: review %>
    <%= render 'reviews/downvote_link', review: review %>
    <br/>
  <% end %>
    		<%= link_to 'reply', new_post_review_path(@post, parent_id: review.id), remote: true, class:"btn btn-secondary" %>
    		 <% if current_user == review.user || current_user.has_role?(:admin) %>
    			<%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
 			 <%end%>
  		</div>
	</div>

	<% if review.replies.any? %>
    <% review.replies.each do |reply| %> 
      <%= render partial: 'reviews/reply', locals: { reply: reply } %>
    <% end %>
    	<br/>
  <% end %>
  <div id="reply-form-<%= review.id %>"></div>
<% end %>

app/views/reviews/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{review.id}" do %>
  <%= link_to upvote_review_path(review), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_up_on? review %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
  <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
</svg>
      remove
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
  <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
</svg>
      upvote
    <% end %>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<%admin_restricted%>
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', posts_path %>

app/views/reviews/like.js.erb
document.getElementById("like-link-<%= @review.id %>").innerHTML = "<%= j render "reviews/like_link", review: @review %>";
document.getElementById("like-count-<%= @review.id %>").innerHTML = "<%= j render "reviews/like_count", review: @review %>";

app/views/reviews/new.js.erb
document.querySelector("#reply-form-<%= @review.parent_id %>").innerHTML = ("<%= j render 'reply_form', review: @review %>")

app/views/reviews/ordered.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboard</h1>
<br/>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User</th>
      <th scope="col">Album</th>
      <th scope="col">Review</th>
      <th scope="col">Score</th>
    </tr>
  </thead>
  <tbody>
    <%count = 0%>
    <% @reviews = Review.all.order(cached_votes_score: :desc) %>
    <% @reviews.each do |review| %>
      <tr>
        <% count = count + 1%>
        <th scope="row"><%= count %></td>
        <td><%= link_to (image_tag review.user.avatar.url, style: 'height:40px;width:40px;'), review.user if review.user.avatar?  %> <%= link_to review.user.username,  review.user %></td>
        <td><%= review.post.title %></td>
        <td style="width:300px"><%= truncate(review.body, :length => 150 )%><%= link_to ' more', review.post %></td>
        <td><%= render 'reviews/like_count', review: review %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/show.html.erb
<%admin_restricted%>
<p id="notice"><%= notice %></p>
<h1 class="text-center"><%= @review.user.username %>'s review of <%= @review.post.title %></h1>
<br/>
<ul class="list-group text-center">
  <li class="list-group-item text-center"><%= @review.body %></li>
  <li class="list-group-item text-left">Review ID: <%= @review.id %></li>
  <li class="list-group-item text-left">Reviewer: <%= link_to @review.user.username, @review.user %></li>
  <li class="list-group-item text-left">Album: <%= link_to @review.post.title, @review.post %></li>
</ul>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', posts_path %>

app/views/reviews/votes.js.erb
document.getElementById("like-count-<%= @review.id %>").innerHTML = "<%= j render "reviews/like_count", review: @review %>";
document.getElementById("downvote-<%= @review.id %>").innerHTML = "<%= j render "reviews/downvote_link", review: @review %>";
document.getElementById("upvote-<%= @review.id %>").innerHTML = "<%= j render "reviews/upvote_link", review: @review %>";